### ISSUE TITLE
Release archive contains .swp files

### ISSUE THREAD

**Issue by htgoebel** [tell-k/sphinxjp.themes.basicstrap#21]
Hi,

the release archive downloaded from PyPI includes at least one .swp file:
`/templates/basicstrap/static/js/.jquery.min.js.swp`.

I suggest adding `global-exclude *.swp` to `MANIFEST.in`.

**Comment by tell-k** [comment]
Sorry too layte my reply. Thanks for your advice.  I've add global-exclude *.swp to MANIFEST.in.
